### ISSUE TITLE
dist/ folder in apikit-node should be pushed so that my project does not have a dependency on coffescript 

### ISSUE THREAD

**Issue by dmartinezg** [mulesoft/osprey-cli#30]

**Comment by 3miliano** [comment]
Marking this as an enhancement.

**Comment by dmartinezg** [comment]
That is your prerogative, I think removing unnecessary dependencies is not an enhancement.  

This, together with the lack of an npm package + the need for us to be on HEAD all the time, make this a blocker.

Otherwise, can you describe a development workflow for us to consume apikit?

**Comment by 3miliano** [comment]
The lack of an NPM package is temporary thing, and therefore this issue will get resolved on its own. The fact that you want to be on HEAD is a different thing, and designing for people who want to be on the bleeding edge is a different use case which is why I'm marking this as an enhancement.

Having said that, it does not mean that we want provide a solution for this. It is just a label for organizing the work.

**Comment by jcenturion** [comment]
I already added 'dist/' folder to the repository since It will also needed for the npm publishing.

Closing this bug.
